import { border, fonts, fontSize, ThemePalette } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createAddExpensesStyles = (colors: ThemePalette) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 8,
      paddingVertical: 12,
      minHeight: 48,
    },
    backBtn: { padding: 8 },
    headerTitle: {
      fontSize: fontSize["lg"],
      fontFamily: fonts.Manrope.Bold,
    },
    headerRight: { width: 40 },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 24, paddingBottom: 24 },
    incomeCard: {
      borderRadius: border.borderRadius.lg,
      borderWidth: 1,
      padding: 16,
      marginBottom: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    incomeCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    incomeCardLabel: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.SemiBold,
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    incomeCardTotal: {
      fontSize: fontSize["2xl"],
      fontFamily: fonts.Manrope.Bold,
    },
    incomeCardTotalSuffix: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.Medium,
    },
    incomeCardBarWrap: {
      height: 8,
      borderRadius: 4,
      flexDirection: "row",
      overflow: "hidden",
      marginTop: 12,
      marginBottom: 10,
    },
    incomeCardBarGreen: {
      height: "100%",
      borderRadius: 4,
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
    },
    incomeCardBarRed: {
      height: "100%",
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
    },
    incomeCardFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    incomeCardRemaining: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.SemiBold,
    },
    incomeCardPercent: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.Medium,
    },
    amountSection: {
      marginTop: 24,
      marginBottom: 24,
    },
    amountLabel: {
      fontSize: fontSize.lg,
      fontFamily: fonts.Manrope.Medium,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      marginBottom: 8,
      textAlign: "center",
    },
    amountExceedsRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      justifyContent: "center",
      marginTop: 12,
    },
    amountExceedsText: {
      flexShrink: 1,
      fontFamily: fonts.Manrope.Medium,
      fontSize: fontSize.sm,
    },
    categorySection: { marginBottom: 20 },
    categoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    viewAll: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.SemiBold,
    },
    categoryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    categoryItem: {
      width: "31%",
      borderRadius: border.borderRadius.lg,
      padding: 12,
      alignItems: "center",
    },
    categoryIconWrap: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    categoryLabel: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.SemiBold,
    },
    field: { marginBottom: 18 },
    fieldLabel: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.SemiBold,
      marginBottom: 8,
    },
    notesInput: {
      minHeight: 100,
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.Medium,
      textAlignVertical: "top",
    },
    footer: {
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 24,
    },
    saveBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    saveBtnText: {
      color: "#fff",
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.Bold,
    },
    modalBackground: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    modalTitle: {
      fontSize: fontSize.lg,
      fontFamily: fonts.Manrope.Bold,
      textAlign: "center",
      paddingVertical: 16,
      paddingHorizontal: 24,
    },
    modalListContent: {
      paddingHorizontal: 24,
      paddingBottom: 34,
    },
    categoryOptionRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    categoryOptionIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 14,
    },
    categoryOptionLabel: {
      flex: 1,
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.SemiBold,
    },
    incomeModalTitle: {
      fontSize: fontSize.lg,
      fontFamily: fonts.Manrope.Bold,
      textAlign: "center",
      paddingVertical: 16,
      paddingHorizontal: 24,
    },
    incomeModalScrollContent: {
      paddingHorizontal: 24,
      paddingBottom: 34,
    },
    incomeSourceCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: 14,
      borderRadius: border.borderRadius.lg,
      borderWidth: 2,
      marginBottom: 12,
    },
    incomeSourceIconWrap: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 14,
    },
    incomeSourceBody: { flex: 1, minWidth: 0 },
    incomeSourceLabel: {
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.Bold,
    },
    incomeSourceRemaining: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.SemiBold,
      marginTop: 2,
    },
    incomeSourceTotal: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.Medium,
      marginTop: 2,
    },
    incomeSourceBarWrap: {
      height: 6,
      borderRadius: 3,
      overflow: "hidden",
      marginTop: 8,
    },
    incomeSourceBarFill: {
      height: "100%",
      borderRadius: 3,
    },
    incomeSourceRight: {
      alignItems: "flex-end",
      marginLeft: 12,
    },
    incomeSourcePct: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.Medium,
      marginBottom: 6,
    },
    incomeSourceRadio: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    incomeSourceRadioInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    incomeSourceConfirmBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 14,
      borderRadius: border.borderRadius.lg,
      marginTop: 8,
    },
    incomeSourceConfirmBtnText: {
      color: "#fff",
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.Bold,
    },
    incomeSourceConfirmBtnWrap: {
      justifyContent: "space-between",
      marginTop: 16,
      padding: 24,
    },
  });
