import { border, fontSize, fonts, ThemePalette } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createTransactionsStyles = (colors: ThemePalette) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.background },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 24,
      marginBottom: 20,
      marginTop: 10,
    },
    filterBtnWrap: {
      position: "relative",
    },
    filterBtn: {
      width: 48,
      height: 48,
      borderRadius: border.borderRadius.lg,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary,
    },
    filterActiveDot: {
      position: "absolute",
      top: -8,
      right: -3,
      width: 20,
      height: 20,
      borderRadius: border.borderRadius.full,
      borderWidth: 2,
      backgroundColor: colors.surfaceVariant,
      borderColor: colors.surfaceVariant,
    },
    scroll: { flex: 1, paddingVertical: 10 },
    scrollContent: { paddingHorizontal: 24, paddingBottom: 120 },
    scrollContentEmpty: {
      flexGrow: 1,
      justifyContent: "center",
      paddingBottom: 80,
    },
    emptyState: {
      alignItems: "center",
      paddingHorizontal: 32,
      paddingVertical: 24,
    },
    emptyIllustrationWrap: {
      maxWidth: "100%",
      alignItems: "center",
    },
    emptyTitle: {
      marginTop: 16,
      fontSize: fontSize.lg,
      fontFamily: fonts.Manrope.Bold,
      textAlign: "center",
      color: colors.textPrimary,
    },
    emptySubtitle: {
      marginTop: 8,
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.Medium,
      textAlign: "center",
      lineHeight: 20,
      color: colors.textSecondary,
    },
    feedbackCard: {
      borderRadius: border.borderRadius.xl,
      borderWidth: 1,
      paddingVertical: 20,
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
      backgroundColor: colors.surfaceContainerHigh,
      borderColor: colors.outlineVariant,
    },
    feedbackTitle: {
      fontSize: fontSize.md,
      fontFamily: fonts.Manrope.Bold,
      textAlign: "center",
      color: colors.textPrimary,
    },
    feedbackSubtitle: {
      marginTop: 6,
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.Medium,
      textAlign: "center",
      color: colors.textSecondary,
    },
    section: { marginBottom: 24 },
    sectionLabel: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.SemiBold,
      letterSpacing: 0.5,
      marginBottom: 12,
      color: colors.textSecondary,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: 14,
      borderRadius: border.borderRadius.lg,
      borderWidth: 1,
      marginBottom: 10,
      backgroundColor: colors.surfaceContainerHigh,
      borderColor: colors.outlineVariant,
    },
    txIconWrap: {
      width: 52,
      height: 52,
      borderRadius: border.borderRadius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    txIconInner: {
      width: 42,
      height: 42,
      borderRadius: border.borderRadius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    txBody: { flex: 1, minWidth: 0 },
    txTitle: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.SemiBold,
      color: colors.textPrimary,
    },
    txSubtitle: {
      fontSize: fontSize.xs,
      fontFamily: fonts.Manrope.Medium,
      marginTop: 2,
      color: colors.textSecondary,
    },
    amountWrap: {
      alignItems: "flex-end",
      marginLeft: 8,
    },
    txAmount: {
      fontSize: fontSize.sm,
      fontFamily: fonts.Manrope.Bold,
      textAlign: "right",
    },
    txTime: {
      fontSize: 10,
      marginTop: 2,
      fontFamily: fonts.Manrope.Medium,
      color: colors.textSecondary,
    },
  });
